### PR TITLE
Add (de)serialization using serde

### PR DESCRIPTION
**Pull request by volks73**
Thank you for creating this crate. I have found it extremely useful in a handful of applications and projects I have been working on. I would like to contribute by adding the ability to serialize and deserialize the Process Unique Identifier (PUID). The serde (https://serde.rs/) crate is used to implement serialization and deserialization. The `Deserialize` and `Serialize` traits are derived using the macros from the serde_derive crate.

I had a need in an application to transmit the Process Unique Id (PUID) over a TCP stream. I was converting the ProcessUniqueId to a string using the Display trait, but I thought it would be more elegant and versatile to implement serialization and deserialization with the serde crate. I think it might be possible to create duplicate PUIDs with deserialization, so this might need to be added with caution. 

I looked at the contribution section of the README and I am okay with the licensing. Please let me know if there is anything else I should do to merge these changes. Thank you.

### CODE REVIEW

**Comment by volks73** [comment]
Whoops, I am sorry. I totally missed the conversation in the other pull request (#7) about (de)serialization. Sorry for the possible duplicate. I used the `#[serde(skip_deserializing, skip_serializing)]` field level macros with types containing a PUID field or variant to avoid the issue with persisting the ID.

**Comment by Stebalien** [comment]
Accidentally creating unintentional duplicates is a possibility but I've decided that I'm fine with that. Thanks!

**Comment by Stebalien** [comment]
Actually, wait. Sorry, I had to revert that merge. Could you open a new PR putting this behind a feature (and document it in the README)? I don't want a simple ID crate to pull in so many dependencies unless required.

**Comment by yrashk** [comment]
And I was wondering for the last 15 minutes why suddenly Cargo refused to fetch the new version:

```
    Updating git repository `https://github.com/Stebalien/snowflake.git`
error: failed to load source for a dependency on `snowflake`

Caused by:
  Unable to update https://github.com/Stebalien/snowflake.git?rev=1f0b898

Caused by:
  [4/-3] Revspec '1f0b898' not found.
```

🤣 🤣 🤣

**Comment by yrashk** [comment]
Can I propose a simpler solution, something like this: https://github.com/PumpkinDB/PumpkinDB/blob/master/pumpkindb_engine/src/script/mod_storage.rs#L437-L444 ?

**Comment by Stebalien** [comment]
Sorry, I thought I had reverted that fast enough that no one would catch me.

I really would like to use a standardized solution like serde, I just don't want to pull it in as a dependency by default. Eventually, we may get ["auto dependencies"](https://github.com/rust-lang/rfcs/pull/1787) or whatever they're called at the moment this problem should go away.

**Comment by yrashk** [comment]
how about a feature-gating this PR?

**Comment by Stebalien** [comment]
> Could you open a new PR putting this behind a feature (and document it in the README)?

**Comment by volks73** [comment]
>Actually, wait. Sorry, I had to revert that merge. Could you open a new PR putting this behind a feature (and document it in the README)? I don't want a simple ID crate to pull in so many dependencies unless required.

No worries. This should be pretty straight-forward and I can put together another PR. I like the idea of making it optional as well.

**Pull request merged**
